name: create-portfolio-tracker-image.yml
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag de la imagen (ej. v1.2.3)"
        required: false
        default: latest
  push:
    branches:
      - main



permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags
        id: tags
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${OWNER_LC}/portfolio-tracker"

          if [ "${{ github.event_name }}" = "push" ]; then
            TAG=$(./gradlew -q :portfolio-tracker:properties | grep "^version:" | awk '{print $2}')
          else
            TAG="${{ github.event.inputs.tag || 'latest' }}"
          fi

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: portfolio-tracker/Dockerfile
          push: true
          tags: |
            ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
            ${{ steps.tags.outputs.image }}:${{ github.sha }}
          secrets: |
            gpr_user=${{ github.actor }}
            gpr_key=${{ secrets.GITHUB_TOKEN }}