name: Only dev can merge to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only PRs from dev to main are allowed."
            exit 1
          fi